### ISSUE TITLE
Dockerize the pipeline

### ISSUE THREAD

**Issue by Shalsh23** [phenoscape/pipeline#107]

**Comment by balhoff** [comment]
Todo:

- [ ] Create docker image containing required tools. See https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile for an example
- [ ] Figure out to how run in Jenkins within this docker environment. We should learn how to use a Jenkinsfile on GitHub to control the Jenkins job (see docker config inside here): https://github.com/geneontology/pipeline/blob/master/Jenkinsfile

**Comment by balhoff** [comment]
Here is the GO Jenkins build: https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/

**Comment by Shalsh23** [comment]
Docker image for the pipeline has been created and uploaded on dockerhub.
