### ISSUE TITLE
requirements.txt fails to install the python libraries required

### ISSUE THREAD

**Issue by Shalsh23** [phenoscape/pipeline#148]
regression.py fails due to statsmodel module not found error
python v2.7.5 required for regression.py

**Comment by hlapp** [comment]
This is for which component?

**Comment by Shalsh23** [comment]
> This is for which component?

This is used in the calculation of `rank statistics` for taxa and genes

**Comment by hlapp** [comment]
I thought we decided a while ago that we were going to replace the python code with the code that the intern at Duke developed.

**Comment by hlapp** [comment]
Or maybe we're talking about different things. Can you point me to the where that python code is that you're trying to support and/or integrate?

**Comment by Shalsh23** [comment]
Yeah, we did decide to replace `regression.py` (https://github.com/phenoscape/pipeline/blob/master/resources/regression.py) with `compute-expect` (https://github.com/phenoscape/compute-expect). But we were just trying to get the pipeline running and then work on the replacement. However, the library versions are proving to be quite an issue as they keep re-surfacing.

**Comment by hlapp** [comment]
I would argue we should spend our efforts on integrating compute-expect, not keeping up with the python code's dependency. (BTW python v2.7.5 is out of support and a security risk.)

**Comment by Shalsh23** [comment]
> I would argue we should spend our efforts on integrating compute-expect, not keeping up with the python code's dependency. (BTW python v2.7.5 is out of support and a security risk.)

@balhoff What so you think?

**Comment by balhoff** [comment]
Yes I think that sounds smart. We can the current version using the python environments we each have working already, and just get to work on the java library.
