### ISSUE TITLE
Downloading data repository doesn't work

### ISSUE THREAD

**Issue by balhoff** [phenoscape/pipeline#169]
This is not working: 

https://github.com/phenoscape/pipeline/blob/23bd090aad3e29837f181872344f5c8f8537908f/Jenkinsfile#L17

If the directory is not there, it is not being downloaded. Please run everything before committing.

**Comment by hlapp** [comment]
BTW when cloning a git repo for some kind of deployment action, i.e. actions which really only need the "desired" (current, tag. etc) version of the repo content, consider doing a shallow clone. Especially for repos containing binary or data files, i.e., files which can be big but lend themselves poorly to version control increments.

**Comment by Shalsh23** [comment]
> This is not working:
> 
> https://github.com/phenoscape/pipeline/blob/23bd090aad3e29837f181872344f5c8f8537908f/Jenkinsfile#L17
> 
> If the directory is not there, it is not being downloaded. Please run everything before committing.

I did test it, that's how I downloaded the repo in the first place. But I didn't realize the importance of the spaces is for more than just aesthetic purposes and probably tweaked it later. My bad.

**Comment by Shalsh23** [comment]
> BTW when cloning a git repo for some kind of deployment action, i.e. actions which really only need the "desired" (current, tag. etc) version of the repo content, consider doing a shallow clone. Especially for repos containing binary or data files, i.e., files which can be big but lend themselves poorly to version control increments. It can speed up the clone several fold.

Thanks for pointing this out!
