### ISSUE TITLE
SLURM job submission script hardcodes email

### ISSUE THREAD

**Issue by hlapp** [phenoscape/pipeline#32]
See [`kb_init.sh`](https://github.com/phenoscape/pipeline/blob/master/kb_init.sh#L4).

**Comment by balhoff** [comment]
@Shalsh23 I'm not sure that we need these scripts in the repo. The starting point should be `make all`—someone can run that wherever they see fit.

However, we will be eventually providing a docker image to make it easier to have the required tools in the environment.
